### POST request to create a new patient entity

POST http://localhost:8080/patients
Content-Type: application/json

{
   "name": "Safwan Irfan",
   "email": "test@gmail.com",
   "address": "123 Karachi, Pakistan",
   "dateOfBirth": "2005-07-23",
   "registeredDate": "2024-11-28"
}